### ISSUE TITLE
Add makefile

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_primary_s3#38]
It should be able to build the app without any dependencies. Ref: https://github.com/owncloud/objectstore/issues/83

Customgroups app has a particular nice makefile https://github.com/owncloud/customgroups/blob/master/Makefile

**Comment by ownclouders** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by SergioBertolinSG** [comment]
Opened PR here: https://github.com/owncloud/files_primary_s3/pull/39

**Comment by patrickjahns** [comment]
Closing - makefile is available here https://github.com/owncloud/files_primary_s3/blob/master/Makefile
