### ISSUE TITLE
Nightly Failure in apiVersions/fileVersions.feature

### ISSUE THREAD

**Issue by grgprarup** [owncloud/files_primary_s3#647]
The recently added tests (https://github.com/owncloud/core/pull/40573) are failing nightly.
Builds: 
https://drone.owncloud.com/owncloud/files_primary_s3/3372/74/20, 
https://drone.owncloud.com/owncloud/files_primary_s3/3373/74/20, 
https://drone.owncloud.com/owncloud/files_primary_s3/3374/74/20,
https://drone.owncloud.com/owncloud/files_primary_s3/3375/74/20

```feature
Scenario: Upload the same file more than twice with the same mtime and only one version is available                                               # /var/www/owncloud/testrunner/tests/acceptance/features/apiVersions/fileVersions.feature:543
    Given user "Alice" has uploaded file "filesForUpload/textfile.txt" to "file.txt" with mtime "Thu, 08 Aug 2019 04:18:13 GMT" using the WebDAV API # FeatureContext::userUploadsFileToWithMtimeUsingTheWebdavApi()
    And user "Alice" has uploaded file "filesForUpload/textfile.txt" to "file.txt" with mtime "Thu, 08 Aug 2019 04:18:13 GMT" using the WebDAV API   # FeatureContext::userUploadsFileToWithMtimeUsingTheWebdavApi()
    When user "Alice" uploads file "filesForUpload/textfile.txt" to "file.txt" with mtime "Thu, 08 Aug 2019 04:18:13 GMT" using the WebDAV API       # FeatureContext::userUploadsFileToWithMtimeUsingTheWebdavApi()
    Then the HTTP status code should be "204"                                                                                                        # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the version folder of file "/file.txt" for user "Alice" should contain "1" element                                                           # FilesVersionsContext::theVersionFolderOfFileShouldContainElements()
      could not find 1 version element(s) in 
      <?xml version="1.0"?>
      <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/dav/meta/2147484628/v/</d:href><d:propstat><d:prop><d:getetag/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/meta/2147484628/v/c4Ywena5CHuFpr6v7t.pcW1fwov4gVi</d:href><d:propstat><d:prop><d:getetag>""d70b40f177b14b470d1756a3c12b963a""</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/meta/2147484628/v/Cs2EEsAOZVK.f7aDvmRMc78ln4PuDyt</d:href><d:propstat><d:prop><d:getetag>""d70b40f177b14b470d1756a3c12b963a""</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
      
      Failed asserting that 2 matches expected 1.
```

**Comment by saw-jan** [comment]
Tests were added in https://github.com/owncloud/core/pull/40573

**Comment by saw-jan** [comment]
Unlike others, here uploading the same file thrice produces 2 versions.

**Comment by phil-davis** [comment]
The core behavior is a bit strange anyway:
1) The 1st upload creates the file - good
2) The 2nd upload creates a version - seems reasonable, the content might be different even if the mtime has been set to the same value, and the files-versions code probably never checks to see if content is exactly the same as what already exists.
3) The 3rd upload does not create a version - a bit strange. I expect that it happens because the mtime of the original file and the 2nd upload are the same. When the 2nd upload is pushed into the version history, it effectively "overwrites" the original upload that is in the version history. I think that versions are keyed by the mtime (they have a Unix timestamp somewhere in the storage naming system)

But for S3 storage, I think that the version storage is done differently, using S3 storage features like https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html

And that versioning implementation probably does not care that the mtime of multiple versions is the same. In a way, that is better behavior.

**Comment by phil-davis** [comment]
Let's skip this test scenario on S3 storage. I think that we tag the scenario `@skip_on_objectstore`
